1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). The second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the resulting array.

In [1]:
import numpy as np

array1 = np.arange(10, 41)
array2 = np.arange(220, 251)
result = array1 + array2
print(result)

[230 232 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264
 266 268 270 272 274 276 278 280 282 284 286 288 290]


2 Generate a two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [2]:
import numpy as np

array = np.arange(100, 100+10*7).reshape(10,7)
print(array)

[[100 101 102 103 104 105 106]
 [107 108 109 110 111 112 113]
 [114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134]
 [135 136 137 138 139 140 141]
 [142 143 144 145 146 147 148]
 [149 150 151 152 153 154 155]
 [156 157 158 159 160 161 162]
 [163 164 165 166 167 168 169]]


3 Generate two one-dimensional arrays with integers between 1-50. The first array should have even integers. The second array should have odd numbers. Finally, multiply each element from the corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [3]:
import numpy as np

even = np.arange(2, 51, 2)
odd = np.arange(1, 51, 2)
result = even * odd
print(result)


[   2   12   30   56   90  132  182  240  306  380  462  552  650  756
  870  992 1122 1260 1406 1560 1722 1892 2070 2256 2450]


4 Generate a two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable by 2 and 5 are present (the numbers must be divisable by both).

In [5]:
import numpy as np

# generate 2D array
array = np.random.randint(1, 1001, size=(40, 5))

# filter array so only numbers divisible by 2 and 5 are present
result = array[(array % 2 == 0) & (array % 5 == 0)]
print(result)

[770 930 650 800 960 950 230 350 360 530 900 100 820 900 190 550 650  40
 850 230 360]
